FROM quay.io/centos/centos:stream8

RUN echo "2021-09-13" > /build_time

RUN dnf -y install NetworkManager\* procps-ng iproute systemd-udev
RUN dnf -y upgrade
RUN echo $'[Unit]\n\
Description=Enable IPv6 in container\n\
[Service]\n\
ExecStart=/usr/sbin/sysctl -w net.ipv6.conf.all.disable_ipv6=0\n\
[Install]\n\
WantedBy=multi-user.target' > /etc/systemd/system/enable_ipv6.service

RUN systemctl enable dbus systemd-udevd NetworkManager enable_ipv6

CMD ["/usr/sbin/init"]
